sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.1'
  - '5.9'
before_install:
  - npm i -g npm@^2.0.0
  - npm install standard ava -g
before_script:
  - npm prune
  - npm run lint
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  only:
    - master
